// src/dtos/contest.dto.ts

export interface CreateContestPayload {
  id?: string; // optional UUID (can be generated by backend)
  matchId?: string;
  title: string;
  description?: string;

  type?: "pre-match" | "live" | "post-match" | string;
  difficulty?: "beginner" | "intermediate" | "expert" | string;

  startAt?: number; // unix seconds
  endAt?: number; // unix seconds

  entryFee?: number;
  prizePool?: number;
  pointsPerQuestion?: number;
  questionsCount?: number;

  totalSpots?: number; // same as maxParticipants
  filledSpots?: number; // current joined participants

  displayEnabled?: boolean;
  isPopular?: boolean;

  joinDeadline?: "before_match" | "fixed_time" | string;
  resultTime?: "end_of_match" | "fixed_time" | string;

  timeCommitment?: string;
  platform?: string;

  status: "scheduled" | "running" | "completed" | "cancelled";
}

export interface UpdateContestPayload extends Partial<CreateContestPayload> {}
